apiVersion: v1
kind: Service
metadata:
  name: jackett-service
spec:
  selector:
    app: jackett
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 9117
