image:
  repository: linuxserver/jackett
  tag: 0.20.3579
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 9117

persistence:
  enabled: true
  size: 1Gi
  storageClass: ""

env:
  - name: PUID
    value: "1000"
  - name: PGID
    value: "1000"
  - name: TZ
    value: "Europe/Oslo"
