replicaCount: 2

environment: development


autoscaling:
  enabled: true
  replicas:
    min: 2
    max: 10
  avgCpuUtilization: 70
  behavior:
    stabilizationWindowSeconds:
      scaleUp: 0
      scaleDown: 120

resources:
  requests:
    cpu: 30m
    memory: 128Mi

image:
  # Set "repository" name of your image for manual Helm install and upgrade.
  repository: browserless/chrome
  tag: 1-puppeteer-19.2.2
  pullPolicy: IfNotPresent

service:
  name: pdf-generator
  type: ClusterIP
  externalPort: 80
  # If your application is running on another port, change only the internal port.
  internalPort: 3000

linkerd:
  enabled: true

monitoring:
  enabled: false
  path: "/metrics"
  port: "3000"

startup:
  enabled: false
  path: "/metrics"

liveness:
  enabled: true
  path: "/metrics"

readiness:
  enabled: true
  path: "/metrics"
