apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "name" . }}
  namespace: {{ .Release.namespace }}
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "name" . }}
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
        release: {{ .Release.Name }}
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if .Values.monitoring.enabled }}
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "3000"
        {{- end }}
        {{- if .Values.linkerd.enabled }}
        linkerd.io/inject: enabled
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
        config.linkerd.io/skip-outbound-ports: "443"
        {{- end }}
    spec:
      serviceAccountName: {{ template "name" . }}
    {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
      {{- range $secret := .Values.image.pullSecrets }}
        - name : {{ $secret.name }}
      {{- end }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ required "A valid image.repository value is required!" .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.image.environment}}
          env:
          {{- range $environment := .Values.image.environment}}
            - name: {{ $environment.name }}
              value: {{ quote $environment.value }}
          {{- end }}
          {{- end }}
          ports:
            - containerPort: {{ .Values.service.internalPort }}
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            {{- if .Values.resources.limits }}
            limits:
              {{- if .Values.resources.limits.cpu }}
              cpu: {{ .Values.resources.limits.cpu }}
              {{- end }}
              {{- if .Values.resources.limits.memory }}
              memory: {{ .Values.resources.limits.memory }}
              {{- end }}
            {{- end }}
          {{- if .Values.startup.enabled}}
          startupProbe:
            httpGet:
              path: {{ .Values.startup.path }}
              port: {{ .Values.service.internalPort }}
          {{- end }}
          {{- if .Values.readiness.enabled}}
          readinessProbe:
            httpGet:
              path: {{ .Values.readiness.path }}
              port: {{ .Values.service.internalPort }}
          {{- end }}
          {{- if .Values.liveness.enabled}}
          livenessProbe:
            httpGet:
              path: {{ .Values.liveness.path }}
              port: {{ .Values.service.internalPort }}
          {{- end }}
        - name: metrics-exporter
          image: ghcr.io/bengtfredh/prometheus-browserless-exporter:6461f8be6c8090085ee0a5d8fe5a4647bf499804
          imagePullPolicy: Always
          env:
            - name: LISTEN_ADDR
              value: ":3001"
            - name: TIMEOUT
              value: "5"
            - name: DEBUG
              value: "TRUE"
            - name: BROWSERLESS_ENDPOINT
              value: "http://localhost:3000/metrics/total"
            - name: METRICS_PATH
              value: "/metrics"
          ports:
            - containerPort: 3001
