{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "name" . }}
  namespace: {{ .Release.namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "name" . }}
  minReplicas: {{ .Values.autoscaling.replicas.min | default 2 }}
  maxReplicas: {{ .Values.autoscaling.replicas.max | default 10 }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.autoscaling.avgCpuUtilization | default 70}}
  behavior:
    scaleDown:
      stabilizationWindowSeconds: {{ .Values.autoscaling.behavior.stabilizationWindowSeconds.scaleDown | default 120 }}
    scaleUp:
      stabilizationWindowSeconds: {{ .Values.autoscaling.behavior.stabilizationWindowSeconds.scaleUp | default 0 }}
{{- end }}
