name: release
on:
  push:
    branches: main

env:
  #HELM_EXPERIMENTAL_OCI: 1 #enable OCI support
  #HELM_VERSION_TO_INSTALL: 3.5.0 # version of HEL to install
  GHCR_IMAGE: ghcr.io/${{ github.repository_owner }}/jackett

jobs:
  build:
    name: publish ghcr
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v3
        name: checkout repo

      - name: Push Helm chart to OCI compatible registry (Github)
        uses: bsord/helm-push@v4
        with:
          useOCIRegistry: true
          registry-url:  oci://ghcr.io/${{ github.repository }}
          username: ${{ github.repository_owner }}
          access-token: ${{ secrets.GITHUB_TOKEN }}
          force: true
          chart-folder: jackett
